spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      orm:
        jdbc:
          bind: trace
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  logging:
    level:
      org:
        hibernate:
          SQL: debug
